/**
 * Catalogue de référence des modèles IA proposés par VerzaRoute.
 * Ces données sont utilisées pour SEEDER Firestore (collection `models`) au premier lancement,
 * et affichées sur la page d'accueil. La marge et l'activation sont ensuite pilotables
 * depuis le dashboard admin (/admin/dashboard/models), Firestore reste la source de vérité en prod.
 *
 * IMPORTANT : le champ `id` (généré par scripts/seed.ts à partir de displayName) doit
 * correspondre EXACTEMENT à l'identifiant de modèle attendu par l'API du fournisseur.
 * Ces identifiants ont été vérifiés par recherche web (juillet 2026) suite à plusieurs
 * erreurs 404/400 "Unknown Model" en production causées par des noms de modèles obsolètes
 * ou mal formatés (points remplacés par des tirets, versions dépréciées, etc.).
 */
import type { AiModel } from "@/types";

export const MODELS_CATALOG: Omit<AiModel, "id">[] = [
  {
    provider: "openai",
    displayName: "GPT-5",
    description: "Le modèle phare d'OpenAI : raisonnement avancé, code, multimodal.",
    contextWindow: 256000,
    inputPricePerMTokUsd: 3,
    outputPricePerMTokUsd: 12,
    marginPercent: 20,
    enabled: true,
    tags: ["raisonnement", "code", "multimodal"],
  },
  {
    provider: "openai",
    displayName: "GPT-5 mini",
    description: "Version rapide et économique de GPT-5 pour un usage quotidien.",
    contextWindow: 128000,
    inputPricePerMTokUsd: 0.4,
    outputPricePerMTokUsd: 1.6,
    marginPercent: 20,
    enabled: true,
    tags: ["rapide", "économique"],
  },
  {
    provider: "anthropic",
    displayName: "Claude Sonnet 5",
    description: "Excellent équilibre qualité/vitesse d'Anthropic, très fort en code et rédaction.",
    contextWindow: 200000,
    inputPricePerMTokUsd: 3,
    outputPricePerMTokUsd: 15,
    marginPercent: 20,
    enabled: true,
    tags: ["code", "rédaction", "raisonnement"],
  },
  {
    provider: "anthropic",
    displayName: "Claude Haiku 4.5",
    description: "Modèle Anthropic rapide et peu coûteux pour les tâches simples à grande échelle.",
    contextWindow: 200000,
    inputPricePerMTokUsd: 0.8,
    outputPricePerMTokUsd: 4,
    marginPercent: 20,
    enabled: true,
    tags: ["rapide", "économique"],
  },
  {
    provider: "google",
    displayName: "Gemini 2.5 Pro",
    description: "Modèle multimodal de Google, très grande fenêtre de contexte.",
    contextWindow: 1000000,
    inputPricePerMTokUsd: 1.25,
    outputPricePerMTokUsd: 5,
    marginPercent: 20,
    enabled: true,
    tags: ["multimodal", "long-contexte"],
  },
  {
    provider: "google",
    displayName: "Gemini 2.5 Flash",
    description: "Version rapide de Gemini, idéale pour les applications temps réel.",
    contextWindow: 1000000,
    inputPricePerMTokUsd: 0.15,
    outputPricePerMTokUsd: 0.6,
    marginPercent: 20,
    enabled: true,
    tags: ["rapide", "économique"],
  },
  {
    provider: "xai",
    displayName: "Grok 4",
    description: "Modèle de xAI, orienté raisonnement et actualité en temps réel.",
    contextWindow: 128000,
    inputPricePerMTokUsd: 3,
    outputPricePerMTokUsd: 15,
    marginPercent: 20,
    enabled: true,
    tags: ["raisonnement", "actualité"],
  },
  {
    provider: "deepseek",
    displayName: "DeepSeek V3",
    description: "Modèle chinois open-weight très performant en code et mathématiques, coût réduit.",
    contextWindow: 128000,
    inputPricePerMTokUsd: 0.27,
    outputPricePerMTokUsd: 1.1,
    marginPercent: 25,
    enabled: true,
    tags: ["code", "mathématiques", "économique"],
  },
  {
    provider: "mistral",
    displayName: "Mistral Large",
    description: "Modèle européen (France) performant en multilingue et raisonnement.",
    contextWindow: 128000,
    inputPricePerMTokUsd: 2,
    outputPricePerMTokUsd: 6,
    marginPercent: 20,
    enabled: true,
    tags: ["multilingue", "raisonnement"],
  },
  {
    provider: "moonshot",
    displayName: "Kimi K2.6",
    description: "Modèle de Moonshot AI, très bon en agents et longues conversations.",
    contextWindow: 256000,
    inputPricePerMTokUsd: 0.6,
    outputPricePerMTokUsd: 2.5,
    marginPercent: 25,
    enabled: true,
    tags: ["agents", "long-contexte"],
  },
  {
    provider: "minimax",
    displayName: "MiniMax M2",
    description: "Modèle chinois polyvalent, bon rapport qualité/prix.",
    contextWindow: 204800,
    inputPricePerMTokUsd: 0.3,
    outputPricePerMTokUsd: 1.2,
    marginPercent: 25,
    enabled: true,
    tags: ["économique", "polyvalent"],
  },
  {
    provider: "zai",
    displayName: "GLM-4.6",
    description: "Modèle Z.ai (Zhipu), fort en code et en usage agentique.",
    contextWindow: 200000,
    inputPricePerMTokUsd: 0.5,
    outputPricePerMTokUsd: 2,
    marginPercent: 25,
    enabled: true,
    tags: ["code", "agents"],
  },
  {
    provider: "stepfun",
    displayName: "Step 2",
    description: "Modèle StepFun, performant en raisonnement multimodal.",
    contextWindow: 128000,
    inputPricePerMTokUsd: 0.5,
    outputPricePerMTokUsd: 2,
    marginPercent: 25,
    enabled: true,
    tags: ["multimodal", "raisonnement"],
  },
  {
    provider: "openai",
    displayName: "GPT Image 1",
    description: "Modèle de génération d'image d'OpenAI, haute fidélité et bonne compréhension des prompts détaillés.",
    contextWindow: 0,
    inputPricePerMTokUsd: 0,
    outputPricePerMTokUsd: 0,
    marginPercent: 25,
    enabled: true,
    tags: ["image", "génération"],
    modality: "image",
    pricePerImageUsd: 0.04,
  },
  {
    provider: "google",
    displayName: "Imagen 4",
    description: "Modèle de génération d'image de Google, excellent rendu photoréaliste.",
    contextWindow: 0,
    inputPricePerMTokUsd: 0,
    outputPricePerMTokUsd: 0,
    marginPercent: 25,
    enabled: true,
    tags: ["image", "génération", "photoréaliste"],
    modality: "image",
    pricePerImageUsd: 0.03,
  },
  {
    provider: "xai",
    displayName: "Grok Image",
    description: "Modèle de génération d'image de xAI, style créatif et réactif.",
    contextWindow: 0,
    inputPricePerMTokUsd: 0,
    outputPricePerMTokUsd: 0,
    marginPercent: 25,
    enabled: true,
    tags: ["image", "génération", "créatif"],
    modality: "image",
    pricePerImageUsd: 0.02,
  },
  {
    provider: "google",
    displayName: "Veo 3.1",
    description: "Modèle de génération vidéo de Google, à partir d'un simple prompt texte. Génération asynchrone (30s à quelques minutes).",
    contextWindow: 0,
    inputPricePerMTokUsd: 0,
    outputPricePerMTokUsd: 0,
    marginPercent: 25,
    enabled: true,
    tags: ["vidéo", "génération", "asynchrone"],
    modality: "video",
    pricePerVideoSecondUsd: 0.35,
  },
];